version: '3.7'

services:

  ecg-tool:
    container_name: ecg-tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/ecg-tool'
      - '/ecg-tool/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

